using MtgForgeLocal.Models;
using Qdrant.Client;
using Qdrant.Client.Grpc;

namespace MtgForgeLocal.Services;

/// <summary>
/// Searches for MTG cards using semantic similarity via Qdrant.
///
/// NOTE: Embeddings are generated by the Python ingestion script using
/// sentence-transformers (all-MiniLM-L6-v2). For search queries we call
/// Ollama's embedding endpoint so we stay fully local without needing
/// Python at runtime.
/// </summary>
public class CardSearchService
{
    private readonly QdrantClient _qdrant;
    private readonly OllamaEmbedService _embedder;
    private readonly ILogger<CardSearchService> _logger;
    private const string Collection = "mtg_cards";

    public CardSearchService(
        QdrantClient qdrant,
        OllamaEmbedService embedder,
        ILogger<CardSearchService> logger)
    {
        _qdrant = qdrant;
        _embedder = embedder;
        _logger = logger;
    }

    /// <summary>Maps a format name to its Qdrant legality payload field.</summary>
    private static string GetLegalityField(string format) => format.ToLowerInvariant() switch
    {
        "standard" => "legality_standard",
        "modern"   => "legality_modern",
        "legacy"   => "legality_legacy",
        "pioneer"  => "legality_pioneer",
        "pauper"   => "legality_pauper",
        "vintage"  => "legality_vintage",
        _          => "legality_commander"
    };

    /// <summary>
    /// Semantic search for cards matching a natural language query.
    /// Optionally filtered by color identity and max price.
    /// </summary>
    public async Task<List<CardSearchResult>> SearchAsync(CardSearchRequest req, CancellationToken ct = default)
    {
        var vector = await _embedder.EmbedAsync(req.Query, ct);

        // Build Qdrant filter conditions
        var conditions = new List<Condition>();

        if (req.Colors?.Count > 0)
        {
            // Color identity must be a subset of the requested colors
            // e.g., for Golgari (B, G) we allow B, G, BG cards
            foreach (var color in req.Colors)
            {
                conditions.Add(new Condition
                {
                    Field = new FieldCondition
                    {
                        Key = "color_identity",
                        Match = new Match { Keyword = color }
                    }
                });
            }
        }

        if (req.MaxPrice.HasValue)
        {
            conditions.Add(new Condition
            {
                Field = new FieldCondition
                {
                    Key = "price_usd",
                    Range = new Qdrant.Client.Grpc.Range
                    {
                        Lte = req.MaxPrice.Value
                    }
                }
            });
        }

        // Format legality filter (replaces hardcoded legality_commander)
        conditions.Add(new Condition
        {
            Field = new FieldCondition
            {
                Key = GetLegalityField(req.Format),
                Match = new Match { Keyword = "legal" }
            }
        });

        var filter = conditions.Count > 0
            ? new Filter { Must = { conditions } }
            : null;

        _logger.LogInformation("Searching Qdrant for: {Query} (limit={Limit})", req.Query, req.Limit);

        var results = await _qdrant.SearchAsync(
            collectionName: Collection,
            vector: vector,
            filter: filter,
            limit: (ulong)req.Limit,
            cancellationToken: ct
        );

        return results.Select(r => new CardSearchResult(
            Name:        r.Payload.GetValueOrDefault("name")?.StringValue ?? "",
            TypeLine:    r.Payload.GetValueOrDefault("type_line")?.StringValue ?? "",
            OracleText:  r.Payload.GetValueOrDefault("oracle_text")?.StringValue,
            ManaCost:    r.Payload.GetValueOrDefault("mana_cost")?.StringValue ?? "",
            Cmc:         r.Payload.GetValueOrDefault("cmc")?.DoubleValue ?? 0,
            PriceUsd:    r.Payload.GetValueOrDefault("price_usd")?.DoubleValue ?? 0,
            ImageUri:    r.Payload.GetValueOrDefault("image_uri")?.StringValue,
            ScryfallUri: r.Payload.GetValueOrDefault("scryfall_uri")?.StringValue,
            Score:       r.Score
        )).ToList();
    }

    /// <summary>
    /// Retrieve a large candidate pool for deck generation.
    /// We intentionally pull more cards than needed and let the LLM curate.
    /// </summary>
    public async Task<List<CardSearchResult>> GetDeckCandidatesAsync(
        DeckRequest req,
        CancellationToken ct = default)
    {
        var isCommander = req.Format.Equals("commander", StringComparison.OrdinalIgnoreCase);

        // Build a rich semantic query from the deck request
        var query = isCommander && req.Commander != null
            ? $"{req.Commander} commander {req.Theme} strategy " +
              $"{string.Join(" ", req.ColorIdentity ?? [])} colors power level {req.PowerLevel}"
            : $"{req.Format} deck {req.Theme} strategy " +
              $"{string.Join(" ", req.ColorIdentity ?? [])} colors power level {req.PowerLevel}";

        // Budget per card: Commander ~70 non-land slots, 60-card formats ~36 spell slots
        var spellSlots = isCommander ? 70.0 : 36.0;
        var perCardBudget = req.Budget / spellSlots;

        return await SearchAsync(new CardSearchRequest(
            Query: query,
            Colors: req.ColorIdentity,
            MaxPrice: perCardBudget * 3, // Allow some expensive staples in the candidate pool
            Limit: 200,
            Format: req.Format
        ), ct);
    }
}
